apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-image-service-g1ho
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-image-service-g1ho
    app.kubernetes.io/part-of: assisted-image-service
  name: assisted-image-service-g1dkj0
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: assisted-image-service-g1ho
    weight: null
status: {}
