apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-image-service-g1ho
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-image-service-g1ho
    app.kubernetes.io/part-of: assisted-image-service
  name: assisted-image-service-g1ho
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: assisted-image-service-g1ho
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: assisted-image-service-g1ho
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-image-service/assisted-image-service-g1ho@sha256:9eba2b56d0cdf1fba89a2999a6927b9cbadd6bb5fe392a554e39722c12a3520c
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
